# Generated by Django 2.2.1 on 2019-06-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matzip_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('review', models.IntegerField(blank=True)),
                ('tv', models.CharField(blank=True, max_length=30)),
                ('biztel', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('Menu', models.TextField(blank=True)),
                ('homepage', models.TextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('blog', models.TextField(blank=True)),
                ('web_site', models.TextField(blank=True)),
                ('convenience', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('graph_1', models.IntegerField(blank=True)),
                ('graph_2', models.IntegerField(blank=True)),
                ('graph_3', models.IntegerField(blank=True)),
                ('graph_4', models.IntegerField(blank=True)),
                ('graph_5', models.IntegerField(blank=True)),
                ('graph_6', models.IntegerField(blank=True)),
                ('Female', models.IntegerField(blank=True)),
                ('male', models.IntegerField(blank=True)),
                ('images', models.TextField(blank=True)),
            ],
        ),
    ]
