# Generated by Django 2.2.1 on 2019-06-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_matzip_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip_list',
            name='biztel',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='category',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='convenience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='store_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='tv',
            field=models.TextField(blank=True),
        ),
    ]
