# Generated by Django 2.2.1 on 2019-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190625_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='graph_6',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
