# Generated by Django 2.2.1 on 2019-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190625_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip_list',
            name='Female',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matzip_list',
            name='male',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
