# Generated by Django 2.2.1 on 2019-06-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190625_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_1',
            new_name='age10',
        ),
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_2',
            new_name='age20',
        ),
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_3',
            new_name='age30',
        ),
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_4',
            new_name='age40',
        ),
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_5',
            new_name='age50',
        ),
        migrations.RenameField(
            model_name='matzip_list',
            old_name='graph_6',
            new_name='age60',
        ),
    ]
