# Generated by Django 2.2.1 on 2019-06-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190625_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matzip_list',
            name='images',
        ),
        migrations.AddField(
            model_name='matzip_list',
            name='images_url',
            field=models.URLField(blank=True),
        ),
    ]
