# Generated by Django 2.2.1 on 2019-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190625_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip_list',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
