# Generated by Django 2.2.1 on 2019-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190625_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matzip_list',
            name='review',
            field=models.IntegerField(blank=True),
        ),
    ]
